### ISSUE TITLE
RubyHW1 feedback

### ISSUE THREAD

**Issue by LVALL** [setwith/RubyHW#1]
Formatting for tasks was intended to be:
```
p "task description"
some code ...
p "result"

```
but it's ok, no need to change

We appreciate you've done 77/50 tasks! Good job 🙌 
The solutions are very good, you've used almost all the methods, except `partition` and `sort by`

They would be fit well for tasks
31 - `sort_by`
2, 66 - `partition`

**Comment by setwith** [comment]
Changed methods for 31, 2, and 66 tasks and used RuboCop for better formatting
