### ISSUE TITLE
Фідбек ДЗ 7

### ISSUE THREAD

**Issue by Kashoid23** [setwith/RubyHW#10]
Круто, що почитали та використали accepts_nested_attributes_for 👍  Чим більше читатимете, тим чистіший буде код.

- [x] Почитайте про всі переваги https://api.rubyonrails.org/classes/ActiveRecord/Enum.html. Особисто я не дуже підтримую використання в скоупах цифрове представлення enum. Enum дозволяє використовувати як ключі так і стрінг для цього, що значно покращує читабельність коду. https://github.com/setwith/RubyHW/blob/main/Blog%20api/app/models/comment.rb#L10-L11
- [x] В кожному наступному ДЗ починаючи з цього, додавайте гем рубокоп (https://github.com/rubocop/rubocop). І перевіряйте свій код в процесі та перед відправкою (команда в консолі - `rubocop`, або `rubocop -a` якщо хочете, щоб рубокоп сам застосував автоформатування коду). Так ви наочно побачите скільки у вас є з форматуванням виправлень.
- [x] Почитайте про `dependent: :destroy` та додайте де це потрібно https://guides.rubyonrails.org/association_basics.html#options-for-belongs-to-dependent
- [x] Ніколи не пуште закоментований код, якщо це не пояснення або TODO
https://github.com/setwith/RubyHW/blob/main/Blog%20api/app/models/author.rb#L6
https://github.com/setwith/RubyHW/blob/main/Blog%20api/app/models/article.rb#L13-L21
Видаліть усі випадки.
- [x] Якщо ви дійсно хочете повертатитеги з артікл, доцільніше визначити змінну після того як атікл буде збережено
https://github.com/setwith/RubyHW/blob/main/Blog%20api/app/controllers/api/v1/articles_controller.rb#L25
Інакще нащо присвоювати значення змінній, якщо повернеться помилка. Також чи є сенс використовувати змінну екземпляра тут?
Те саме тут https://github.com/setwith/RubyHW/blob/main/Blog%20api/app/controllers/api/v1/likes_controller.rb#L4
- [x] Назвіть просто `latest` скоуп і так доступний лише для коментарів https://github.com/setwith/RubyHW/blob/main/Blog%20api/app/models/comment.rb#L13
- [x] У вас два подібних випадки вирішені по різному
@article.tags ви спочатку додаєте в змінну
@article.likes просто передаєте з json (мені наразі це більше довподоби)
Намагайтесь дотримуватись одного стилю написання коду.
https://github.com/setwith/RubyHW/blob/main/Blog%20api/app/controllers/api/v1/articles_controller.rb#L19-L20
- [x] Ви продублювали `order(created_at: :desc)`. Це один з тригерів для вас винести це в скоуп.
https://github.com/setwith/RubyHW/blob/main/Blog%20api/app/controllers/api/v1/authors_controller.rb#L15
Якщо ви бачите, що код повторюється це завжди має заохочувати подумати, як позбутись дублікації.
- [x] Чи варто було використати before_action set_author?
https://github.com/setwith/RubyHW/blob/main/Blog%20api/app/controllers/api/v1/authors_controller.rb#L20
https://github.com/setwith/RubyHW/blob/main/Blog%20api/app/controllers/api/v1/authors_controller.rb#L14
- [x] Чому просто в запиті не передавати параметр status та оновлювати його в екшині?
https://github.com/setwith/RubyHW/blob/main/Blog%20api/app/controllers/api/v1/comments_controller.rb#L18-L23

**Comment by setwith** [comment]
Дякую! Проапдейтив код враховуючи правки 🙂
