### ISSUE TITLE
Feedback for HW6

### ISSUE THREAD

**Issue by MaksHostroushko** [setwith/RubyHW#11]
1. https://github.com/setwith/RubyHW/blob/main/Blog%20api/app/controllers/api/v1/comments_controller.rb#L44
Scale your before_action and remove duplication from `update_status` method
I mean
`@comment = Comment.find(params[:id].presence || params[:comment_id])`
```
def update_status
  new_status = @comment.status == 'unpublished' ? 'published' : 'unpublished'
  @comment.update(status: new_status)

  render json: @comment, notice: "Comment updated to #{@comment.status} "
end
```

2. https://github.com/setwith/RubyHW/blob/main/Blog%20api/app/controllers/api/v1/comments_controller.rb#L20
Let's get value from model enum values instead of hardcoded strings
Also, move the logic for choosing of new status to the private method
```
def update_status
  @comment.update(status: new_status)
  render json: @comment, notice: "Comment updated to #{@comment.status} "
end

def new_status
  return Article.statuses[:published]  if @comment.status == :unpublished 
  
  Article.statuses[:unpublished]
end
```

3.https://github.com/setwith/RubyHW/blob/main/Blog%20api/app/models/comment.rb#L10..L11
Hardcoded values it's not the best way in the context of code style of logic in general
So, please use a tip from the previous comment and get value from the model's enum values

**Comment by setwith** [comment]
Дякую! Проапдейтив код враховуючи правки 🙂
