### ISSUE TITLE
HW8 Feedback

### ISSUE THREAD

**Issue by DmytrioO** [setwith/RubyHW#13]
I want to say that in general the work is not bad. But it has some nuances:
1. In ArticleController, on index method, when you making pagination - you use all available articles instead of filtered ones. Because of this, we do not see the filtered list of articles when make the GET-request. Please, change the articles_controller.rb on line 26 from this: @pagy, @articles = pagy(Article.order(created_at: :desc), items: 15) to this: @pagy, @articles = pagy(@articles.order(created_at: :desc), items: 15). A similar problem exists for the order request.
2. I think, that filtering by tags, if we write more than one tag, should return only those articles that have all of the specified tags at once, not those that have at least one. But it's only my opinion.
3. Please, add a page-info(variable @pagy in your code) to the ArticlesController#index response. It will be show us an information about the number of pages, the number of the current page, the number of entries on the page, and the like.
4. According to the condition of the task, with the ArticlesController#show-method, only the name of the author should be returned in the response, and not all his information. Please fix it!
No more problems were noticed and I think it's a good job.

**Comment by setwith** [comment]
Дякую! Проапдейтив код враховуючи правки 🙂
