### ISSUE TITLE
Фідбек ДЗ 8

### ISSUE THREAD

**Issue by Kashoid23** [setwith/RubyHW#16]
Все окей.

- [x] Схоже в цьому https://github.com/setwith/RubyHW/blob/main/HW8/app/controllers/api/v1/articles_controller.rb#L74-L76 немає потреби
- [x] Фільтр по статусу не працюватиме https://github.com/setwith/RubyHW/blob/main/HW8/app/models/article.rb#L19
- [x] Перейменуйте params на query https://github.com/setwith/RubyHW/blob/main/HW8/app/models/article.rb#L18
- [x] Створіть серіалайзер для автора який буде повертати лише імя. Та апдейтніть серіалазер коментарів, типу has_one: author, щоб від застосовував серіалайзер та повертав лише імя автора

**Comment by setwith** [comment]
Дякую! Оновив код враховуючи всі правки)
