### ISSUE TITLE
Ревью до домашки (HW3)

### ISSUE THREAD

**Issue by EugeneShitov** [setwith/RubyHW#2]
***Чи запускається код без помилок?!***

Гем 42 працює супер 👍🏻
Гем для HTML гуд 👍🏽
Тамагочі робить 👍🏿

---

***З приводу написання коду (по стилю)***

`class.rb`
1. Замість `if змінна == 0` використовуй `if змінна.zero?`
2. В методі потрбно бути до 10 рядків включно (якщо більше - рубокоп свариться)
3. У стрічці рекомендують писати не більше 120 символів (в деяких місцях є перевищення)
4. Назва методів повинна бути у snake_case, та може містити лише '[_a-z][_a-z0-9]*[!?=]?'
5. У тебе 6 рядків з такою помилкою `puts 'енергія = ' + @energy.to_s`
юзай інтерполяцію рядків `puts "енергія = #{@energy}"`
6. Дуже багато `@name.capitalize`, замість цього зроби в файлі `game.rb` так - `name = gets.chomp.capitalize` 

Як там кажуть?! Don't Repeat Yourself? 🙃 

---

`game.rb`

 Тут все гуд

**Comment by setwith** [comment]
Done!)

**Comment by Kashoid23** [comment]
Хороша робота 🔥

- [x] Використайте константу замість `phrases` та прочитайте (використайте) про freeze

https://www.educative.io/answers/how-to-freeze-objects-in-ruby
```
phrases = [
      'А ти знав, що на нашій шкірі може жити більше живих організмів, ніж людей на всій планеті?',
      'А ти знав, що три найбагатші родини у світі мають більше активів, ніж 48 найбідніших країн?',
      'А ти знав, що кубик Рубіка – товар, який найбільше продається у світі. На другому місці – iPhone?',
      'А ти знав, що чотирирічна дитина в середньому ставить 400 запитань на день?',
      'А ти знав, що на шоломах астронавтів є спеціальний пристрій, щоб чухати носа?',
      'А ти знав, що якби до Coca-Cola не додавали барвник, вона була б зеленого кольору?'
    ]
```

- [x] Використайте attr_reader, attr_writer, attr_accessor замість змінних екземпляра, де можливо. Це довзволить звертатись (оновлювати) до аттрибутів без змінних екземпляра

```
class Pet
  def initialize(name)
    @name = name.capitalize
    @health = 20
    @happiness = 20
    @stuff_in_belly = 20
    @asleep = false
    @workout = 20
    @energy = 20

    puts "Хей, мене звати #{@name}, і тепер я планую любити тебе та проводити багато часу разом. Давай пошвидше знайдемо заняття для нас!)"
  end
```

- [x] Переробіть в одну умову, без повторного присвоювання

@emoji = if ...
elsif ...
elsif ...

```
@emoji = '&#128567;' if @health < 5
    @emoji = '&#128511;' if @happiness < 5
    @emoji = '&#128528;' if @stuff_in_belly < 5
    @emoji = '&#128565;' if @workout < 5
    @emoji = '&#128128;' if @energy < 5
```

- [x] Схоже гем залитий на рубіджемс, тоді для чого це?

```
require 'bundler'
Bundler.require
```

**Comment by setwith** [comment]
Modified

**Comment by Kashoid23** [comment]
Супер! 🚀 
@EugeneShitov закрий, будь ласка, іш'ю
