### ISSUE TITLE
Feedback HW2 arrays

### ISSUE THREAD

**Issue by RoRElessar** [setwith/RubyHW#3]
Do not shrink the variables. If you are declaring a variable called `e` - it is not clear what it means. Call it something like `element`. In the future, you will have some large blocks of codes where you should understand the meaning of the variable. For example, if you declare a user instance - the variable should be called `user`, but not `u`.

**Comment by setwith** [comment]
Fixed

**Comment by RoRElessar** [comment]
- [x] https://github.com/setwith/RubyHW/blob/1fd8a46bc26df4aed43433c58573daa459ab2f78/HW2/task1.rb#L4
Why are you repeating the code above? Isn't it better to do it like this: `p "arr = #{arr}"`?

**Comment by setwith** [comment]
Valid remark. Modified
