### ISSUE TITLE
Feedback HW2 Tamagotchi

### ISSUE THREAD

**Issue by RoRElessar** [setwith/RubyHW#4]
- [x] Rename your `class.rb` file to `pet.rb`. Naming is very important. You shouldn't call your files in the way you did. When you open a directory and see files in it - it should be clear what it contains.

- [x] Fix typos in your variables and methods: `@happyness`, `@asllep`, `check_worckout`

- [x] `puts phrases.sample + 'Так, знаю, міг би поступити в Гарвард :D'` - use string interpolation. Everywhere in the code you are using it, but for some reason, you don't use it here.

- [x] Do not use camel case for your methods and variables - rename them please, so they fit a snake case.

- [x] `@name.capitalize` DRY it, please.

**Comment by setwith** [comment]
Resolved all tasks
