### ISSUE TITLE
Feedback HW4 Tamagotchi with rack

### ISSUE THREAD

**Issue by alinajuly** [setwith/RubyHW#5]
Чудова гра, зрозумілий код, маю всього декілька зауважень :)

- [x]  https://github.com/setwith/RubyHW/blob/9bccd4eced258fc7a5d5dac00d5d90128bec1a2a/Tamagotchi_rack/app/application.rb#L32
в application.rb багато повторювань коду, можливо краще винести окремо, наприклад, в метод alive і використовувати його

- [x] виправити пару синтаксичних помилок "Рівень нергії", "ти обіймаєте"

- [x] відчуття ситості не піднімається вище 19, улюбленець постійно голодний))

**Comment by setwith** [comment]
Таски виконав)

Відчуття ситості навмисно обмежив на такому рівні, щоб пета необхідно було періодично кормити 🙂
