### ISSUE TITLE
HW 5 feedback

### ISSUE THREAD

**Issue by LVALL** [setwith/RubyHW#8]
Хороша і охайна робота, зручно, що додані записи в `seeds.rb`, коректно використано `before_action` колбек

лише декілька мінорних коментарів:

- [x] статуси варто додавати до всіх респонзів, тому [тут](https://github.com/setwith/RubyHW/blob/a41c3405c2d27376485d8de511168b0d7e9e5db5/Blog%20api/app/controllers/api/v1/articles_controller.rb#L24) варто додати `status: :ok` https://guides.rubyonrails.org/layouts_and_rendering.html#the-status-option

- [x] метод `destroy` не гарантовано буде успішним, його виконанню можуть завадити валідації моделі, зв'язки, чи якісь інші фактори, саме тому для нього, як і для методів `create`, `update` в контролері, потрібно додати опрацювання негативного результату (коли запис не було видалено). 

- [x] Почитайте про контролери детальніше тут: https://guides.rubyonrails.org/action_controller_overview.html

**Comment by setwith** [comment]
Дякую, відредагував врахувавши коментарі 🙂
