### ISSUE TITLE
HW6

### ISSUE THREAD

**Issue by EduardKurbanov** [setwith/RubyHW#9]
Базовая релализацыя кода правельна но есть нюансы.

----------------------------------------------
Рекомендация.

В routers.rb допешы resources :authors, :articles, :comments слово onli: [] -  для тех методов которые у тебя есть, бо в rails routes  ,а но выводит все пути даже не существующих, вот пример на твой код.
```ruby
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :authors, only: [:index, :create]
      resources :articles, only: [:index, :show, :create, :update, :destroy] do
        resources :comments, only: [:index, :show, :create, :update, :destroym, :published, :unpublished, :update_status]
        get :published_comments
        get :unpublished_comments
        patch :update_status
      end
    end
  end
end 
```
------------------------------------------------

у тебя нет привязки автора к статьи в create Article,
невозможно создать article по запросу
```ruby
POST   /api/v1/articles(.:format)      api/v1/articles#create
```
ошыбка 
```ruby
{
    "author": [
        "must exist"
    ]
}
```
---------------------------------------------------
```ruby
db/seeds.rb
```
у тебя в Article.create не указон id автора, пример:
```ruby
Article.create([
                 {
                   title: 'First article',
                   body: 'Some text for article',
                   author_id: 1
                 },
```
----------------------------------------------------
```ruby
db/seeds.rb
```
и Comment.create нету поля status:, пример:
```ruby
Comment.create([
                 {
                   body: 'First comment by John',
                   status: "published",
                   author_id: 1,
                   article_id: 1
                 },
```
-----------------------------------------------------

это то что я нашол.

**Comment by setwith** [comment]
Виправив, дякую
